### ISSUE TITLE
build fails - missing GreenBlueKnob.cpp (0.4.0)

### ISSUE THREAD

**Issue by PatchworkBoy** [Phal-anx/MS-Modules#2]
Build failing in v0.4.0 on MacOS10.13

```
MCO-rMBP:plugins marci$ git clone https://github.com/Phal-anx/MS-Modules.git
Cloning into 'MS-Modules'...
remote: Counting objects: 187, done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 187 (delta 105), reused 187 (delta 105), pack-reused 0
Receiving objects: 100% (187/187), 83.41 KiB | 431.00 KiB/s, done.
Resolving deltas: 100% (105/105), done.
MCO-rMBP:plugins marci$ cd MS-Modules/
MCO-rMBP:MS-Modules marci$ git submodule update --init --recursive
MCO-rMBP:MS-Modules marci$ make
c++ -fPIC -I../../include -I../../dep/include -DVERSION=dev -DVERSION_dev -MMD -O3 -march=nocona -ffast-math -g -Wall -DARCH_MAC -mmacosx-version-min=10.7 -std=c++11 -stdlib=libc++ -c -o build/src/GreenBlueSmall.cpp.o src/GreenBlueSmall.cpp
c++ -fPIC -I../../include -I../../dep/include -DVERSION=dev -DVERSION_dev -MMD -O3 -march=nocona -ffast-math -g -Wall -DARCH_MAC -mmacosx-version-min=10.7 -std=c++11 -stdlib=libc++ -c -o build/src/MS_modules.cpp.o src/MS_modules.cpp
c++ -fPIC -I../../include -I../../dep/include -DVERSION=dev -DVERSION_dev -MMD -O3 -march=nocona -ffast-math -g -Wall -DARCH_MAC -mmacosx-version-min=10.7 -std=c++11 -stdlib=libc++ -c -o build/src/RandomSource.cpp.o src/RandomSource.cpp
src/RandomSource.cpp:2:10: fatal error: 'GreenBlueKnob.cpp' file not found
#include "GreenBlueKnob.cpp"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [build/src/RandomSource.cpp.o] Error 1
```

**Comment by Phal-anx** [comment]
yea that was a known issue ... (build you downloaded does only work in 0.3.2)

the actual source code is for 0.4.0... changed it today  
pls let me know if this own works

**Comment by PatchworkBoy** [comment]
Yup - minor warning, but builds n’ works fine - cheers!

**Comment by Phal-anx** [comment]
could you post me the warning? ... on my windows system i dont get one
